services:
  - type: web
    name: heatmap-oficinas
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 1
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11